### ISSUE TITLE
reduce_v7有问题

### ISSUE THREAD

**Issue by zhzq123** [Liu-xiandong/How_to_optimize_in_GPU#1]
把ai 改成随机赋值，会发现结果有误
目前测出 reduce_v4 还是没问题的。

**Comment by Liu-xiandong** [comment]
感谢您提的bug，非常抱歉现在才回复您，我会在近期修复bug :)

**Comment by Liu-xiandong** [comment]
> 把ai 改成随机赋值，会发现结果有误 目前测出 reduce_v4 还是没问题的。
感谢您提的bug，非常抱歉现在才回复您，我会在近期修复bug :)

**Comment by Liu-xiandong** [comment]
> 把ai 改成随机赋值，会发现结果有误 目前测出 reduce_v4 还是没问题的。

目前已经修复，欢迎再次试用
