### ISSUE TITLE
最后一次小迭代时register数据预取

### ISSUE THREAD

**Issue by hwchen2017** [Liu-xiandong/How_to_optimize_in_GPU#10]
最后一次小迭代时register数据预取没有在code中实现，应该在大迭代的syncthreads之后加上，不然结果肯定是错的

**Comment by Liu-xiandong** [comment]
> 最后一次小迭代时register数据预取没有在code中实现，应该在大迭代的syncthreads之后加上，不然结果肯定是错的

感谢你的建议~ 目前代码确实有一些bug，我会尽快修复，预计本周内，感谢支持 ~

**Comment by Liu-xiandong** [comment]
@hwchen2017 你好，bug已经修复了哈，感谢提问~
