### ISSUE TITLE
请问 sgemm 的程序是哪里改动改错了吗？性能不大行？

### ISSUE THREAD

**Issue by hermosayhl** [Liu-xiandong/How_to_optimize_in_GPU#11]
我运行 sgemm_v3.cu 的结果是这样的

![image](https://user-images.githubusercontent.com/49510831/188070824-379c738e-10f9-41a6-82f7-df1c5534a5e1.png)

我的 CMakeLists.txt 是这样的，请问哪里错了吗？漏了编译选项？
```CMake
PROJECT(opencv_dnn_demo)

cmake_minimum_required(VERSION 3.5)

add_definitions(-w)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR})

# set(CMAKE_CXX_STANDARD 14)
# add_compile_options(-std=c++11)
# add_compile_options(-O3)
SET(CMAKE_CXX_FLAGS "-std=c++11 -O1")

# CUDA
find_package(CUDA REQUIRED)
set(CUDA_NVCC_FLAGS -G;-g; -arch=sm_70)
# (可执行文件, 源码)
cuda_add_executable(executor sgemm.cu)

set(CUDA_LIBRARY_DIRS "${CUDA_HOME}/lib64")
link_directories(${CUDA_LIBRARY_DIRS})
set(CUDA_LIBRARIES cudart cublas)
target_link_libraries(executor ${CUDA_LIBRARIES})
```

**Comment by hermosayhl** [comment]
我使用的是 M = N = K = 1024。
如果换成 M = N = K = 4096，结果也不对
![image](https://user-images.githubusercontent.com/49510831/188073011-7a53a874-6f71-4769-91ae-4d474637fecd.png)

**Comment by Liu-xiandong** [comment]
你好，已经收到了你的信息，我会在这两天确认一下，看看是哪里的问题，感谢提问哈~

**Comment by Liu-xiandong** [comment]
@hermosayhl Hi,这是我使用的编译命令和运行命令：
```
nvcc -O3 -o sgemm sgemm_v3.cu -gencode=arch=compute_70,code=\"sm_70,compute_70\" -lcublas
./sgemm 4096 4096 4096
```
得到的结果如下：
![image](https://user-images.githubusercontent.com/85323580/188350885-9bc8f26b-5e1c-4348-b44f-e5b10a6610c0.png)
可以试试哈~

**Comment by hermosayhl** [comment]
> @hermosayhl Hi,这是我使用的编译命令和运行命令：
> 
> ```
> nvcc -O3 -o sgemm sgemm_v3.cu -gencode=arch=compute_70,code=\"sm_70,compute_70\" -lcublas
> ./sgemm 4096 4096 4096
> ```
> 
> 得到的结果如下： ![image](https://user-images.githubusercontent.com/85323580/188350885-9bc8f26b-5e1c-4348-b44f-e5b10a6610c0.png) 可以试试哈~

嗷嗷，好的好的，我回去试试。谢谢 ！
