### ISSUE TITLE
reduction优化技巧3

### ISSUE THREAD

**Issue by MGLiXu** [Liu-xiandong/How_to_optimize_in_GPU#2]
num_per_block变成4倍或者8倍，还可以继续提升很多？

**Comment by Liu-xiandong** [comment]
> num_per_block变成4倍或者8倍，还可以继续提升很多？

我做过实验，实际上是不行的。做到reduce_v5的时候已经接近理论极限了，在reduce_v5的基础上再用shuffle会有一定提升。但是提高num_per_block是没有必要的。
