### ISSUE TITLE
" ** On entry to SGEMM  parameter number 13 had an illegal value" warning?

### ISSUE THREAD

**Issue by Arsmart123** [Liu-xiandong/How_to_optimize_in_GPU#5]
![image](https://user-images.githubusercontent.com/65449458/166234854-d089b027-4062-486f-89cb-94b3d93cdd75.png)
Hi! I met this.....And I am a new user of cublas, not sure why this happens..I searched it on google, and they said this is related to different cuda version. Not sure whether this will provide incorrect answer or just simply warning....

**Comment by Liu-xiandong** [comment]
> ![image](https://user-images.githubusercontent.com/65449458/166234854-d089b027-4062-486f-89cb-94b3d93cdd75.png) Hi! I met this.....And I am a new user of cublas, not sure why this happens..I searched it on google, and they said this is related to different cuda version. Not sure whether this will provide incorrect answer or just simply warning....

You can see this, [https://github.com/xianyi/OpenBLAS/issues/1014](https://github.com/xianyi/OpenBLAS/issues/1014)

Suggest you to check the values values of m and ldc. Make sure that ldc is not less than m.

Thanks.
