### ISSUE TITLE
Results of cublas and sgemm_v3.cu differ

### ISSUE THREAD

**Issue by chaoming0625** [Liu-xiandong/How_to_optimize_in_GPU#9]
Dear @Liu-xiandong , the matrix multiplication results of the source code of ``sgemm_v3.cu`` differs from than of cublas. How can we solve it? Thanks.

**Comment by Liu-xiandong** [comment]
> Dear @Liu-xiandong , the matrix multiplication results of the source code of `sgemm_v3.cu` differs from than of cublas. How can we solve it? Thanks.

There seems to be some bugs, I will fix it next week.

**Comment by Liu-xiandong** [comment]
@chaoming0625 Hello，the  bug is fixed. Welcome to use it.

**Comment by chaoming0625** [comment]
Excellent!
